#!/bin/bash

# Check (and default) the parameters.
host=$1
num=$2
start=$3
chunk=$4
if [ "$host" = "" ] || [ "$num" = "" ]
then
  echo "Usage: $0 <host> <number of users to make> [<first user index> [<chunk size>]]" >&2
  exit 1
fi
if [ "$start" = "" ]
then
  start=1
fi
if [ "$chunk" = "" ]
then
  chunk=1000
fi
end=$((start + num - 1))

index=0
while [ $((start + index * chunk)) -lt $end ]
do
  range_start=$((start + index * chunk))
  range_end=$((start + index * chunk + chunk - 1))
  if [ $range_end -gt $end ]
  then
    range_end=end
  fi
  ./make_callload_users $1 $((range_end - range_start + 1)) $range_start > callload_users.csv.$index &
  index=$((index + 1))
done

while [ $index -gt 0 ]
do
  wait
  index=$((index - 1))
done

cat callload_users.csv.* > callload_users.csv
rm callload_users.csv.*
