#!/bin/bash
#
# merge_callload_lines
#
# Merges lines in user files.  This is required because our callload script
# requires two users per line, rather than just one (which make_callload_users
# generates).
#
# Usage: merge_callload_lines <file with one user per line>

# Check the parameter.
file=$1
if [ "$file" = "" ]
then
  echo "Usage: $0 <file with one user per line>" >&2
  exit 1
fi

# Pass the file through awk to merge consecutive lines (separating them with a
# semi-colon, and then through sed to strip the semi-colon from the first
# (unmerged) line.
<$file awk '(NR%2){print p";"$0}{p=$0}' | sed -e 's/^;SEQUENTIAL$/SEQUENTIAL/g'
