#!/bin/sh

# @file check-sprout-uptime
#
# Copyright (C) Metaswitch Networks 2017
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

# Monit 5.8.1 does not support passing arguments to check program scripts.
# check-uptime provides common uptime-checking code. This wrapper script
# uses it, and can be called with no arguments.
/usr/share/clearwater/bin/check-uptime /var/run/sprout/sprout.pid monit 1000.1
