#!/bin/bash

# @file create-analytic-syslog-config
#
# Project Clearwater - IMS in the Cloud
# Copyright (C) 2016 Metaswitch Networks Ltd
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version, along with the "Special Exception" for use of
# the program along with SSL, set forth below. This program is distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details. You should have received a copy of the GNU General Public
# License along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
# The author can be reached by email at clearwater@metaswitch.com or by
# post at Metaswitch Networks Ltd, 100 Church St, Enfield EN2 6BQ, UK
#
# Special Exception
# Metaswitch Networks Ltd  grants you permission to copy, modify,
# propagate, and distribute a work formed by combining OpenSSL with The
# Software, or a work derivative of such a combination, even if such
# copying, modification, propagation, or distribution would otherwise
# violate the terms of the GPL. You must comply with the GPL in all
# respects for all of the code used other than OpenSSL.
# "OpenSSL" means OpenSSL toolkit software distributed by the OpenSSL
# Project and licensed under the OpenSSL Licenses, or a work based on such
# software and licensed under the OpenSSL Licenses.
# "OpenSSL Licenses" means the OpenSSL License and Original SSLeay License
# under which the OpenSSL Project distributes the OpenSSL toolkit software,
# as those licenses appear in the file LICENSE-OPENSSL.

# This file creates a syslog config file for Sprout's analytics logs.

syslog_conf_file=/etc/rsyslog.d/30-sproutanalytics.conf
temp_file=$(mktemp sproutanalytics.syslog.XXXXXXXX)

. /etc/clearwater/config

if [ -n "$remote_audit_logging_server" ]; then
  # If a remote syslog server is configured for auditing registrations, we need
  # an rsyslog config line for directing the correct syslogs to this server. We
  # use a regex to forward messages that start with the correct tag and are
  # registrations.
  remote_syslog_audit_server_str=":msg, regex, \"<analytics>.*Registration:.*\" @@${remote_audit_logging_server}"
fi

# Add tls setup to the top of the config file if the option is specified
shopt -s nocasematch
if [[ $remote_audit_logging_use_tls == "y" ]]; then
  cat > $temp_file << EOF
\$ActionSendStreamDriver gtls

# Certificate files
\$DefaultNetstreamDriverCAFile /etc/clearwater/ent/rsyslog-ca.crt
\$DefaultNetstreamDriverCertFile /etc/clearwater/ent/rsyslog-client.crt
\$DefaultNetstreamDriverKeyFile /etc/clearwater/ent/rsyslog-client.key

\$ActionSendStreamDriverAuthMode x509/certvalid
\$ActionSendStreamDriverMode 1

EOF
fi
shopt -u nocasematch

cat >> $temp_file << EOF
\$FileCreateMode 0666
\$umask 0000

# Define a template that strips the "<analytics>" tag off the front of it.  This
# actually strips 14 characters off the message because we also strip off the
# leading whitespace that rsyslog adds in order to conform with RFC3164 syslog
# format, but that we don't want.
\$template analytics-format,"%msg:14:$%\r\n"

:msg, contains, "<analytics>" /var/log/sprout/analytics.log;analytics-format
$remote_syslog_audit_server_str
:msg, contains, "<analytics>" stop

\$FileCreateMode 0644
EOF

if ! diff $temp_file $syslog_conf_file > /dev/null 2>&1
then
  # Update the config file.
  mv $temp_file $syslog_conf_file

  # Restart rsyslog to pick up the new config file.
  service rsyslog restart
else
  rm $temp_file
fi
