Gem::Specification.new do |s|
  s.name        = 'clearwater-sipp-stats'
  s.version     = '1.0.0'
  s.date        = '2013-04-15'
  s.summary     = "Statistics server for SIPp stress nodes"
  s.description = "Statistics server for SIPp stress nodes.  Parses the counts CSV file generated by SIPp and reports a select subset over 0MQ"
  s.authors     = ["Andy Caldwell"]
  s.email       = 'andrew.caldwell@metaswitch.com'
  s.homepage    = 'http://projectclearwater.org'
  s.license     = 'GPL3'

  s.bindir      = "bin"
  s.files       = ["lib/clearwater-sipp-stats.rb"]
  s.executables << "clearwater-sipp-stats"

  s.add_dependency 'ffi-rzmq'
end
