#!/bin/bash

# @file sprout-stability
#
# Copyright (C) Metaswitch Networks 2017
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

# Used for monitoring the stability of the sprout process.

PROCESS_NAME="sprout"
GRACE_PERIOD=20

method=$1

/usr/share/clearwater/bin/process-stability $method $PROCESS_NAME $GRACE_PERIOD
exit $?
