build/bin/sprout_scscf.so usr/share/clearwater/sprout/plugins

# Install the IFCs plugins and scripts
modules/clearwater-etcd-plugins/clearwater_config_manager/shared_ifcs_xml_plugin.py /usr/share/clearwater/clearwater-config-manager/plugins/
modules/clearwater-etcd-plugins/clearwater_config_manager/fallback_ifcs_xml_plugin.py /usr/share/clearwater/clearwater-config-manager/plugins/
modules/clearwater-etcd-plugins/clearwater_config_manager/scripts/remove_shared_ifcs_xml /usr/share/clearwater/clearwater-config-manager/scripts
modules/clearwater-etcd-plugins/clearwater_config_manager/scripts/remove_fallback_ifcs_xml /usr/share/clearwater/clearwater-config-manager/scripts
modules/clearwater-etcd-plugins/clearwater_config_manager/scripts/validate_shared_ifcs_xml /usr/share/clearwater/clearwater-config-manager/scripts
modules/clearwater-etcd-plugins/clearwater_config_manager/scripts/validate_fallback_ifcs_xml /usr/share/clearwater/clearwater-config-manager/scripts
modules/clearwater-etcd-plugins/clearwater_config_manager/scripts/display_shared_ifcs /usr/share/clearwater/clearwater-config-manager/scripts
modules/clearwater-etcd-plugins/clearwater_config_manager/scripts/display_fallback_ifcs /usr/share/clearwater/clearwater-config-manager/scripts
modules/clearwater-etcd-plugins/clearwater_config_manager/scripts/config_validation/* /usr/share/clearwater/clearwater-config-manager/scripts/config_validation

modules/clearwater-etcd-plugins/clearwater_config_access/shared_ifcs_config_plugin.py /usr/share/clearwater/clearwater-config-access/plugins/
modules/clearwater-etcd-plugins/clearwater_config_access/fallback_ifcs_config_plugin.py /usr/share/clearwater/clearwater-config-access/plugins/
