#!/bin/bash
ONE_GIG=1073741824
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/bono --prefix bono_ --maxsize $ONE_GIG
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/bono --prefix log_ --maxsize $ONE_GIG
