#!/bin/bash
ONE_GIG=1073741824
WEEK_COUNT=168
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/sprout --prefix sprout_ --maxsize $ONE_GIG --count $WEEK_COUNT
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/sprout --prefix log_ --maxsize $ONE_GIG --count $WEEK_COUNT
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/sprout --prefix access_ --maxsize $ONE_GIG --count $WEEK_COUNT
