#!/bin/bash

# Copyright (C) Metaswitch Networks
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

FILENAME=enum.json
KEY=enum_json

# Pass optional argument directly to upload_json, which checks for --allow-large
# option that allows file upload larger than advisable
/usr/share/clearwater/clearwater-config-manager/scripts/upload_json $FILENAME $KEY $1
