#!/bin/bash

# Copyright (C) Metaswitch Networks 2017
# If license terms are provided to you in a COPYING file in the root directory
# of the source code repository by which you are accessing this code, then
# the license outlined in that COPYING file applies to your use.
# Otherwise no rights are granted except for those provided to you by
# Metaswitch Networks in a separate written agreement.

FILENAME=mmf_targets.json
KEY=mmf_targets_json
SCHEMA=/usr/share/clearwater/clearwater-config-manager/scripts/config_validation/mmf_targets_schema.json

# Pass optional argument directly to upload_json, which checks for --allow-large
# option that allows file upload larger than advisable
/usr/share/clearwater/clearwater-config-manager/scripts/upload_generic_json $FILENAME $KEY $SCHEMA $@

rc=$?
if [[ $rc == 0 ]]; then
  echo "Successfully uploaded the new MMF targets configuration"
fi

exit $rc
